package dev.saga.messaging;
public enum Type {
 ORDER_CREATED, RESERVE_INVENTORY, INVENTORY_RESERVED, INVENTORY_REJECTED,
 CHARGE_PAYMENT, PAYMENT_CHARGED, PAYMENT_REJECTED,
 BOOK_SHIPMENT, SHIPMENT_BOOKED, SHIPMENT_REJECTED,
 CANCEL_SAGA, CANCEL_SHIPMENT, SHIPMENT_CANCELLED,
 REFUND_PAYMENT, PAYMENT_REFUNDED, RELEASE_INVENTORY, INVENTORY_RELEASED
}
